/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import com.toedter.calendar.JDateChooser;
import java.util.Date;
import entities.Employe;
import entities.Absence;
import entities.TypeAbsence;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import services.Absenceservice;

/**
 *
 * @author aithmad
 */
public class Ajouter_Absence extends javax.swing.JFrame {

    /**
     * Creates new form Ajouter_Absence
     */
    Principal principal = null;

    public Ajouter_Absence(Principal principal) {
        initComponents();
        this.principal = principal;
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        charger_employe_type_box();
    }
    
    public void charger_employe_type_box(){
        List<Employe> list_employe = principal.employeservice.getAllemplye();
        List<TypeAbsence> list_type = principal.typeabsenceservise.getAllTypeabsence();
        
        for(Employe e : list_employe){
            employetxt.addItem(e);
        }
        
        for(TypeAbsence type : list_type){
            type_absencetxt.addItem(type);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        datedebuttxt = new com.toedter.calendar.JDateChooser();
        datefintxt = new com.toedter.calendar.JDateChooser();
        type_absencetxt = new javax.swing.JComboBox();
        employetxt = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ajouterAbsence = new javax.swing.JButton();
        btnannulerajouter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(37, 138, 122));

        jLabel4.setFont(new java.awt.Font("URW Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(233, 247, 245));
        jLabel4.setText("AJOUTER UNE ABSENCE");

        jLabel1.setForeground(new java.awt.Color(233, 247, 245));

        jLabel2.setForeground(new java.awt.Color(233, 247, 245));
        jLabel2.setText("Employé");

        jLabel3.setForeground(new java.awt.Color(233, 247, 245));
        jLabel3.setText("Date de début d’absence");

        jLabel5.setForeground(new java.awt.Color(233, 247, 245));
        jLabel5.setText("Date de fin d'absence");

        jLabel6.setForeground(new java.awt.Color(233, 247, 245));
        jLabel6.setText("Type d'absence");

        ajouterAbsence.setBackground(new java.awt.Color(97, 189, 114));
        ajouterAbsence.setFont(new java.awt.Font("URW Gothic", 1, 15)); // NOI18N
        ajouterAbsence.setText("Ajouter");
        ajouterAbsence.setBorderPainted(false);
        ajouterAbsence.setOpaque(true);
        ajouterAbsence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterAbsenceActionPerformed(evt);
            }
        });

        btnannulerajouter.setBackground(new java.awt.Color(191, 215, 85));
        btnannulerajouter.setFont(new java.awt.Font("URW Gothic", 1, 15)); // NOI18N
        btnannulerajouter.setText("Annuler");
        btnannulerajouter.setBorderPainted(false);
        btnannulerajouter.setOpaque(true);
        btnannulerajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnannulerajouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ajouterAbsence, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnannulerajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(employetxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(datedebuttxt, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                            .addComponent(datefintxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(type_absencetxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel4)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datedebuttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datefintxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(type_absencetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouterAbsence)
                    .addComponent(btnannulerajouter))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterAbsenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterAbsenceActionPerformed
        Date date_debut = datedebuttxt.getDate();
        Date date_fin = datefintxt.getDate();
        Employe employe = (Employe) employetxt.getSelectedItem();
        TypeAbsence typeabsence = (TypeAbsence) type_absencetxt.getSelectedItem();

        Absenceservice as = new Absenceservice();

        if (datedebuttxt == null || date_fin == null || employe == null || typeabsence == null) {
            JOptionPane.showMessageDialog(this,"Un champ manquant","Important",
                    JOptionPane.WARNING_MESSAGE);
        } else {

            int choix = JOptionPane.showConfirmDialog(
                    this,
                    "Voullez-vous vraiment ajouter cette absence ?",
                    "Confermation",
                    JOptionPane.OK_CANCEL_OPTION
            );
            if (choix == JOptionPane.OK_OPTION) {

                Absence absence = new Absence(date_debut, date_fin, employe, typeabsence);
                as.createAbsence(absence);
                principal.charger_Absence_Table();
                principal.charger_Employe_Table();
                JOptionPane.showMessageDialog(this, "Absence ajoutée avec succès");
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_ajouterAbsenceActionPerformed

    private void btnannulerajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnannulerajouterActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnannulerajouterActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterAbsence;
    private javax.swing.JButton btnannulerajouter;
    private com.toedter.calendar.JDateChooser datedebuttxt;
    private com.toedter.calendar.JDateChooser datefintxt;
    private javax.swing.JComboBox employetxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox type_absencetxt;
    // End of variables declaration//GEN-END:variables
}
