/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import services.Employeservice;
import entities.Employe;
import javax.swing.JOptionPane;
import UI.Principal;
import javax.swing.JFrame;

/**
 *
 * @author aithmad
 */
public class Ajouter_Employe extends javax.swing.JFrame {

    private Principal apprincipal;

    /**
     * Creates new form Ajouteremploye
     */
    public Ajouter_Employe(Principal app) {
        initComponents();
        this.apprincipal = app;
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomEajouter = new javax.swing.JTextField();
        btnEajouter = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnannulerAjouterEM = new javax.swing.JButton();
        boxDepartement = new javax.swing.JComboBox();
        boxPoste = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AJouter employe");

        jPanel1.setBackground(new java.awt.Color(37, 138, 122));

        jLabel1.setForeground(new java.awt.Color(233, 247, 245));
        jLabel1.setText("Nom");

        jLabel2.setForeground(new java.awt.Color(233, 247, 245));
        jLabel2.setText("Poste");

        jLabel3.setForeground(new java.awt.Color(233, 247, 245));
        jLabel3.setText("Departement");

        txtNomEajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomEajouterActionPerformed(evt);
            }
        });

        btnEajouter.setBackground(new java.awt.Color(97, 189, 114));
        btnEajouter.setFont(new java.awt.Font("URW Gothic", 1, 15)); // NOI18N
        btnEajouter.setText("Ajouter");
        btnEajouter.setBorderPainted(false);
        btnEajouter.setOpaque(true);
        btnEajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEajouterActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("URW Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(233, 247, 245));
        jLabel4.setText("AJOUTER UN EMPLOYE");

        btnannulerAjouterEM.setBackground(new java.awt.Color(191, 215, 85));
        btnannulerAjouterEM.setFont(new java.awt.Font("URW Gothic", 1, 15)); // NOI18N
        btnannulerAjouterEM.setText("Annuler");
        btnannulerAjouterEM.setBorderPainted(false);
        btnannulerAjouterEM.setOpaque(true);
        btnannulerAjouterEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnannulerAjouterEMActionPerformed(evt);
            }
        });

        boxDepartement.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Développement", "Réseau", "RH", "Finance" }));
        boxDepartement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxDepartementActionPerformed(evt);
            }
        });

        boxPoste.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Développeur", "Testeur", "Chef de projet", "Scrum Master", "Technicien Réseau", "Admin Système", "Technicien Support", "Responsable RH", "Assistant RH", "Responsable Formation", "Chargée Recrutement", "Chargé Recrutement", "Comptable", "Responsable Financier", "Contrôleur", "Assistant Comptable", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxDepartement, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(txtNomEajouter)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnEajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                    .addComponent(btnannulerAjouterEM, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel3)
                                .addComponent(boxPoste, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel4)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomEajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxDepartement, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxPoste, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEajouter)
                    .addComponent(btnannulerAjouterEM))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomEajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomEajouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomEajouterActionPerformed

    private void btnEajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEajouterActionPerformed
        String nom = txtNomEajouter.getText();
        String departement = boxDepartement.getSelectedItem().toString();
        String poste = boxPoste.getSelectedItem().toString();
        Employeservice employeservice = new Employeservice();
        Employe e = new Employe(nom, departement, poste);

        if (nom.isEmpty() || departement.isEmpty() || poste.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Un champ manquant",
                    "important",JOptionPane.WARNING_MESSAGE);
        } else {

            int choix = JOptionPane.showConfirmDialog(
                    this,
                    "Voulez-vous vraiment ajouter cet employé ?",
                    "Confermation",
                    JOptionPane.OK_CANCEL_OPTION
            );
            if (choix == JOptionPane.OK_OPTION) {
                employeservice.createEmplye(e);
                apprincipal.charger_Employe_Table();
                apprincipal.charger_graphe_employe();
                JOptionPane.showMessageDialog(this, "Employé ajouté avec succès");
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_btnEajouterActionPerformed

    private void btnannulerAjouterEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnannulerAjouterEMActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnannulerAjouterEMActionPerformed

    private void boxDepartementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxDepartementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxDepartementActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox boxDepartement;
    private javax.swing.JComboBox boxPoste;
    private javax.swing.JButton btnEajouter;
    private javax.swing.JButton btnannulerAjouterEM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNomEajouter;
    // End of variables declaration//GEN-END:variables
}
