/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import UI.Principal;
import entities.Absence;
import javax.swing.JOptionPane;
import entities.TypeAbsence;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aithmad
 */
public class Chercher_Typeabsence extends javax.swing.JFrame {

    /**
     * Creates new form Chercher_Typeabsence
     */
    Principal principal = null;
    private int id_selected = -1;

    public Chercher_Typeabsence(Principal principal) {
        initComponents();
        this.principal = principal;
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public JTextField getLibelle() {
        return libelle;
    }

    public int getId_selected() {
        return id_selected;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        libelle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        chercher = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        supprimer = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_employe_trouves = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(37, 138, 122));

        jLabel1.setFont(new java.awt.Font("URW Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(244, 253, 252));
        jLabel1.setText("CHERCHER TYPE D'ABSENCE");

        libelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libelleActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(252, 245, 245));
        jLabel2.setText("Libellé du type à rechercher");

        chercher.setBackground(new java.awt.Color(157, 233, 177));
        chercher.setFont(new java.awt.Font("URW Gothic", 1, 15)); // NOI18N
        chercher.setText("Chercher");
        chercher.setBorderPainted(false);
        chercher.setOpaque(true);
        chercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chercherActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(238, 247, 248));
        jLabel3.setText("Type d'absence trouvés");

        supprimer.setBackground(new java.awt.Color(215, 85, 85));
        supprimer.setFont(new java.awt.Font("URW Gothic", 1, 15)); // NOI18N
        supprimer.setText("Supprimer");
        supprimer.setBorderPainted(false);
        supprimer.setOpaque(true);
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        modifier.setBackground(new java.awt.Color(233, 215, 157));
        modifier.setFont(new java.awt.Font("URW Gothic", 1, 15)); // NOI18N
        modifier.setText("Modifier");
        modifier.setBorderPainted(false);
        modifier.setOpaque(true);
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        annuler.setBackground(new java.awt.Color(191, 215, 85));
        annuler.setFont(new java.awt.Font("URW Gothic", 1, 15)); // NOI18N
        annuler.setText("Annuler");
        annuler.setBorderPainted(false);
        annuler.setOpaque(true);
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        table_employe_trouves.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "libelle", "justification"
            }
        ));
        table_employe_trouves.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_employe_trouvesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_employe_trouves);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chercher, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(libelle, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 110, Short.MAX_VALUE)))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(supprimer)
                            .addComponent(modifier)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(libelle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(chercher)
                        .addGap(18, 18, 18)
                        .addComponent(annuler)))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void libelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libelleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_libelleActionPerformed

    private void chercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chercherActionPerformed
        String lib = libelle.getText();
        List<TypeAbsence> type_trouve = new ArrayList<>();

        if (lib.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Le champ est vide",
                    "Important",JOptionPane.WARNING_MESSAGE);
        } else {
            type_trouve = principal.typeabsenceservise.getTypeBylibelle(lib);

            if (type_trouve.size() == 0) {
                DefaultTableModel model = (DefaultTableModel) table_employe_trouves.getModel();
                model.setRowCount(0);
                JOptionPane.showMessageDialog(this, lib + " non trouvable");
                libelle.setText("");
                model.setNumRows(0);
            } else {
                JOptionPane.showMessageDialog(this, lib + " trouvé avec succès");
                DefaultTableModel model = (DefaultTableModel) table_employe_trouves.getModel();
                model.setRowCount(0);

                for (TypeAbsence t : type_trouve) {
                    model.addRow(new Object[]{
                        t.getId(),
                        t.getLibelle(),
                        t.getJustification()
                    });
                }
            }
        }

    }//GEN-LAST:event_chercherActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        DefaultTableModel model = (DefaultTableModel) table_employe_trouves.getModel();
        if (model.getRowCount() != 0) {
            if (id_selected != -1) {
                int choix = JOptionPane.showConfirmDialog(
                        this,
                        "Voulez-vous vraiment supprimer ce type d'absence ?",
                        "Confirmation",
                        JOptionPane.OK_CANCEL_OPTION
                );
                if (choix == JOptionPane.OK_OPTION) {
                    this.principal.typeabsenceservise.deleteTypeabsence(
                            principal.typeabsenceservise.getTypeabsenceByid(id_selected));

                    this.principal.charger_TypesAbsence_Table();
                    JOptionPane.showMessageDialog(this, "Type d'absence supprimé avec succès");
                    libelle.setText("");
                    model.setRowCount(0);
                    id_selected = -1;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Aucun type d'absence sélectionné",
                        "Important",JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Aucun type trouvé\n"
                    + "Veuillez en chercher un");
        }


    }//GEN-LAST:event_supprimerActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        DefaultTableModel model = (DefaultTableModel) table_employe_trouves.getModel();

        if (model.getRowCount() != 0) {
            if (id_selected != -1) {
                ModifierTypeRechPnl modifierType = new ModifierTypeRechPnl(this);
                modifierType.setLocationRelativeTo(null);
                modifierType.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Aucun type sélectionné pour la modification",
                        "Important",JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Aucun type trouvé.\nVeuillez en chercher un");
        }
    }//GEN-LAST:event_modifierActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_annulerActionPerformed

    private void table_employe_trouvesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_employe_trouvesMouseClicked
        int selectedRow = table_employe_trouves.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) table_employe_trouves.getModel();
            id_selected = Integer.parseInt(model.getValueAt(selectedRow, 0).toString());
        }
    }//GEN-LAST:event_table_employe_trouvesMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler;
    private javax.swing.JButton chercher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField libelle;
    private javax.swing.JButton modifier;
    private javax.swing.JButton supprimer;
    private javax.swing.JTable table_employe_trouves;
    // End of variables declaration//GEN-END:variables
}
