/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import UI.Principal;
import java.util.List;
import entities.TypeAbsence;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class Modifier_TypeAbsence extends javax.swing.JFrame {

    private Principal principal = null;
    private int type_id_selected ;

    public Modifier_TypeAbsence(Principal principal , int id ) {
        initComponents();
        this.principal = principal;
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.type_id_selected = id ;

    }

    public JTextField getTxtnewjustification() {
        return txtnewjustification;
    }

    public JTextField getTxtnewlibelle() {
        return txtnewlibelle;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnewjustification = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnewlibelle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btannulerMTypeA = new javax.swing.JButton();
        btnmodifierTypeA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(37, 138, 122));

        jLabel1.setForeground(new java.awt.Color(233, 247, 245));
        jLabel1.setText("Nouveau libelle");

        txtnewjustification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnewjustificationActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(233, 247, 245));
        jLabel3.setText("Nouvelle justification");

        txtnewlibelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnewlibelleActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("URW Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(233, 247, 245));
        jLabel4.setText("MODIFIER TYPE D'ABSENCE");

        btannulerMTypeA.setBackground(new java.awt.Color(191, 215, 85));
        btannulerMTypeA.setFont(new java.awt.Font("URW Gothic", 1, 15)); // NOI18N
        btannulerMTypeA.setText("Annuler");
        btannulerMTypeA.setBorderPainted(false);
        btannulerMTypeA.setOpaque(true);
        btannulerMTypeA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btannulerMTypeAActionPerformed(evt);
            }
        });

        btnmodifierTypeA.setBackground(new java.awt.Color(233, 215, 157));
        btnmodifierTypeA.setFont(new java.awt.Font("URW Gothic", 1, 15)); // NOI18N
        btnmodifierTypeA.setText("Modifier");
        btnmodifierTypeA.setBorderPainted(false);
        btnmodifierTypeA.setOpaque(true);
        btnmodifierTypeA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifierTypeAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnmodifierTypeA, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(btannulerMTypeA, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtnewlibelle)
                    .addComponent(txtnewjustification))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnewlibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnewjustification, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmodifierTypeA)
                    .addComponent(btannulerMTypeA))
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnewjustificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnewjustificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnewjustificationActionPerformed

    private void txtnewlibelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnewlibelleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnewlibelleActionPerformed

    private void btannulerMTypeAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btannulerMTypeAActionPerformed
        this.setVisible(false);
        this.setVisible(false);
    }//GEN-LAST:event_btannulerMTypeAActionPerformed

    private void btnmodifierTypeAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifierTypeAActionPerformed
        String new_libelle = txtnewlibelle.getText();
        String new_justification = txtnewjustification.getText();

        TypeAbsence Type_modifier = principal.typeabsenceservise.getTypeabsenceByid(type_id_selected);
        Type_modifier.setLibelle(new_libelle);
        Type_modifier.setJustification(new_justification);
        

        if (new_libelle.isEmpty() || new_justification.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Un champ manquant","Important",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            int choix = JOptionPane.showConfirmDialog(
                    this,
                    "Voulez-vous vraiment modifier ce type d'absence ?",
                    "Confirmation",
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE
            );
            if (choix == JOptionPane.OK_OPTION) {
                principal.typeabsenceservise.updateTypeabsence(Type_modifier);
                principal.charger_TypesAbsence_Table();
                JOptionPane.showMessageDialog(this, "Type d'absence modifié avec succès");
                this.setVisible(false);
            }
            principal.type_id_selected = -1 ;
        }
    }//GEN-LAST:event_btnmodifierTypeAActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btannulerMTypeA;
    private javax.swing.JButton btnmodifierTypeA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtnewjustification;
    private javax.swing.JTextField txtnewlibelle;
    // End of variables declaration//GEN-END:variables
}
