/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import UI.Modifier_TypeAbsence ;
import java.awt.HeadlessException;
import entities.TypeAbsence ;
import javax.swing.JFrame;
import javax.swing.JOptionPane ;

/**
 *
 * @author aithmad
 */
public class ModifierTypeRechPnl extends javax.swing.JFrame {

    /**
     * Creates new form ModifierTypeRechPnl
     */
    Chercher_Typeabsence prin ;
    
    public ModifierTypeRechPnl(String string) throws HeadlessException {
        super(string);
    }

    public ModifierTypeRechPnl(Chercher_Typeabsence principal) {
        initComponents();
        this.prin = principal ;
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        newjustification = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        newlibelle1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        annuler1 = new javax.swing.JButton();
        modifier1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(37, 138, 122));

        jLabel6.setForeground(new java.awt.Color(233, 247, 245));
        jLabel6.setText("Nouveau libelle");

        newjustification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newlebelleActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(233, 247, 245));
        jLabel9.setText("Nouveau justification");

        newlibelle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newlibelleActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("URW Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(233, 247, 245));
        jLabel10.setText("MODIFIER TYPE D'ABSENCE");

        annuler1.setBackground(new java.awt.Color(191, 215, 85));
        annuler1.setFont(new java.awt.Font("URW Gothic", 1, 15)); // NOI18N
        annuler1.setText("Annuler");
        annuler1.setBorderPainted(false);
        annuler1.setOpaque(true);
        annuler1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        modifier1.setBackground(new java.awt.Color(233, 215, 157));
        modifier1.setFont(new java.awt.Font("URW Gothic", 1, 15)); // NOI18N
        modifier1.setText("Modifier");
        modifier1.setBorderPainted(false);
        modifier1.setOpaque(true);
        modifier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(modifier1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(annuler1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6)
                        .addComponent(jLabel9)
                        .addComponent(newlibelle1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                        .addComponent(newjustification)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addGap(51, 51, 51)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newlibelle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newjustification, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifier1)
                    .addComponent(annuler1))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        String new_lib = newlibelle1.getText();
        String new_justification = newjustification.getText();

        TypeAbsence type_modifier = this.prin.principal.typeabsenceservise.getTypeabsenceByid(prin.getId_selected()); ;
        type_modifier.setLibelle(new_lib);
        type_modifier.setJustification(new_justification);

        if (new_lib.isEmpty() || new_justification.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Un champ manquant","Important",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            int choix = JOptionPane.showConfirmDialog(
                this,
                "Voulez-vous vraiment modifier ce type ?",
                "Confirmation",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE
            );
            if (choix == JOptionPane.OK_OPTION) {
                this.prin.principal.typeabsenceservise.updateTypeabsence(type_modifier);
                this.prin.principal.charger_TypesAbsence_Table();
                JOptionPane.showMessageDialog(this, "Type d'absence modifié avec succès");
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_modifierActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_annulerActionPerformed

    private void newlibelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newlibelleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newlibelleActionPerformed

    private void newlebelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newlebelleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newlebelleActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton modifier1;
    private javax.swing.JTextField newjustification;
    private javax.swing.JTextField newlibelle1;
    // End of variables declaration//GEN-END:variables
}
