/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import entities.Employe;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.List;
import entities.TypeAbsence;
import java.util.Date;
import javax.swing.JOptionPane;
import entities.Absence;

/**
 *
 * @author aithmad
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Principal principal;
    int id_absence_selected;

    public NewJFrame(Principal principal, int id) {
        initComponents();
        this.principal = principal;
        this.charger_option();
        this.id_absence_selected = id;
    }

    public void charger_option() {
        List<Employe> employes = this.principal.employeservice.getAllemplye();
        List<TypeAbsence> typeabsences = this.principal.typeabsenceservise.getAllTypeabsence();

        for (Employe e : employes) {
            employebox.addItem(e);
        }
        for (TypeAbsence t : typeabsences) {
            typebox.addItem(t);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        employebox = new javax.swing.JComboBox();
        typebox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        newdatedebutbox = new com.toedter.calendar.JDateChooser();
        newdatefinbox = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        modierabsencebtn = new javax.swing.JButton();
        btannulerMenploye = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(37, 138, 122));

        jLabel4.setFont(new java.awt.Font("URW Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(233, 247, 245));
        jLabel4.setText("MODIFIER L'ABSENCE");

        jLabel2.setForeground(new java.awt.Color(233, 247, 245));
        jLabel2.setText("Nouvel employé");

        jLabel3.setForeground(new java.awt.Color(233, 247, 245));
        jLabel3.setText("Nouveau Type d'absence");

        jLabel5.setForeground(new java.awt.Color(233, 247, 245));
        jLabel5.setText("Nouveau date de debut");

        jLabel6.setForeground(new java.awt.Color(233, 247, 245));
        jLabel6.setText("Nouveau date de fin");

        modierabsencebtn.setBackground(new java.awt.Color(233, 215, 157));
        modierabsencebtn.setFont(new java.awt.Font("URW Gothic", 1, 15)); // NOI18N
        modierabsencebtn.setText("Modifier");
        modierabsencebtn.setBorderPainted(false);
        modierabsencebtn.setOpaque(true);
        modierabsencebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modierabsencebtnActionPerformed(evt);
            }
        });

        btannulerMenploye.setBackground(new java.awt.Color(191, 215, 85));
        btannulerMenploye.setFont(new java.awt.Font("URW Gothic", 1, 15)); // NOI18N
        btannulerMenploye.setText("Annuler");
        btannulerMenploye.setBorderPainted(false);
        btannulerMenploye.setOpaque(true);
        btannulerMenploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btannulerMenployeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newdatedebutbox, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typebox, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(128, 128, 128)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(87, 87, 87)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(employebox, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(modierabsencebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btannulerMenploye, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(newdatefinbox, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employebox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(typebox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newdatedebutbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newdatefinbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modierabsencebtn)
                    .addComponent(btannulerMenploye))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modierabsencebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modierabsencebtnActionPerformed
        Date new_date_debut = newdatedebutbox.getDate();
        Date new_date_fin = newdatefinbox.getDate();
        Employe new_employe = (Employe) employebox.getSelectedItem();
        TypeAbsence new_typeabsence = (TypeAbsence) typebox.getSelectedItem();

        if (new_date_debut == null || new_date_fin == null || new_employe == null || new_typeabsence == null) {
            JOptionPane.showMessageDialog(this, "Un champ est manquant",
                    "Important",JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (principal == null || principal.absenceservice == null) {
            JOptionPane.showMessageDialog(this, "Service d'absence non disponible!");
            return;
        }

        Absence a = principal.absenceservice.getAbsenceByid(this.id_absence_selected);
        if (a == null) {
            JOptionPane.showMessageDialog(this, "Absence introuvable !");
            return;
        }

        a.setDate_debut(new_date_debut);
        a.setDate_fin(new_date_fin);
        a.setEmploye(new_employe);
        a.setTypeabence(new_typeabsence); // attention à l’orthographe du setter

        int choix = JOptionPane.showConfirmDialog(
                this,
                "Voulez-vous vraiment modifier cette absence ?",
                "Confirmation",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (choix == JOptionPane.OK_OPTION) {
            principal.absenceservice.updateAbsence(a);
            principal.charger_Absence_Table();
            JOptionPane.showMessageDialog(this, "Absence modifiée avec succès");
            this.setVisible(false);
        }

    }//GEN-LAST:event_modierabsencebtnActionPerformed

    private void btannulerMenployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btannulerMenployeActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btannulerMenployeActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btannulerMenploye;
    private javax.swing.JComboBox employebox;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modierabsencebtn;
    private com.toedter.calendar.JDateChooser newdatedebutbox;
    private com.toedter.calendar.JDateChooser newdatefinbox;
    private javax.swing.JComboBox typebox;
    // End of variables declaration//GEN-END:variables
}
