/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import connexion.User;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author aithmad
 */
public class Reanitilisation_Password extends javax.swing.JFrame {

    /**
     * Creates new form Reanitilisation_Password
     */
    private Recuperation_Email principal;

    public Reanitilisation_Password(Recuperation_Email principal) {
        initComponents();
        this.principal = principal;
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        new_passtxt1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        code_recuptxt = new javax.swing.JTextField();
        btnEajouter = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnannulerajouter = new javax.swing.JButton();
        new_passtxt2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(37, 138, 122));

        jLabel1.setForeground(new java.awt.Color(233, 247, 245));
        jLabel1.setText("Code de récupération");

        new_passtxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_passtxt1ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(233, 247, 245));

        jLabel3.setForeground(new java.awt.Color(233, 247, 245));
        jLabel3.setText("Nouveau mot de passe");

        code_recuptxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                code_recuptxtActionPerformed(evt);
            }
        });

        btnEajouter.setBackground(new java.awt.Color(97, 189, 114));
        btnEajouter.setFont(new java.awt.Font("URW Gothic", 1, 15)); // NOI18N
        btnEajouter.setText("Changer");
        btnEajouter.setBorderPainted(false);
        btnEajouter.setOpaque(true);
        btnEajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEajouterActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("URW Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(233, 247, 245));
        jLabel4.setText("REANITIALISATION ");

        btnannulerajouter.setBackground(new java.awt.Color(191, 215, 85));
        btnannulerajouter.setFont(new java.awt.Font("URW Gothic", 1, 15)); // NOI18N
        btnannulerajouter.setText("Annuler");
        btnannulerajouter.setBorderPainted(false);
        btnannulerajouter.setOpaque(true);
        btnannulerajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnannulerajouterActionPerformed(evt);
            }
        });

        new_passtxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_passtxt2ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(233, 247, 245));
        jLabel5.setText("Confirmation du mot de passe");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(btnannulerajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(new_passtxt2)
                            .addComponent(new_passtxt1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(code_recuptxt, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(code_recuptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(new_passtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(new_passtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnannulerajouter)
                    .addComponent(btnEajouter))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void new_passtxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_passtxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_passtxt1ActionPerformed

    private void code_recuptxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_code_recuptxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_code_recuptxtActionPerformed

    private void btnEajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEajouterActionPerformed
        String new_pass = new_passtxt1.getText();
        String ver_new_pass = new_passtxt2.getText();
        String code_recup_saisi = code_recuptxt.getText();
        String hashed_new_password = this.principal.principal.md5(new_pass);

        if (new_pass.isEmpty() || ver_new_pass.isEmpty() || code_recup_saisi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Un champ manquant",
                    "Important",JOptionPane.WARNING_MESSAGE);
        } else {
            if (code_recup_saisi.equals(this.principal.getCode().toString())) {

                if (new_pass.equals(ver_new_pass)) {
                    try {
                        User.update_pass_word(hashed_new_password, this.principal.getEmail());
                        JOptionPane.showMessageDialog(this, "Mot de passe réinitialisé avec "
                                + "succès.\nVeuillez vous connecter avec le nouveau.");
                        this.setVisible(false);

                    } catch (Exception e) {
                        System.out.println("Erreur dans la mise à jour du mot de passe");
                        JOptionPane.showMessageDialog(this, "Un problème est survenu, "
                                + "veuillez réessayer.");
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Les deux mots de passe"
                            + " ne correspondent pas.");
                }

            } else {
                JOptionPane.showMessageDialog(this, "Le code est incorrect, "
                        + "veuillez réessayer.");
                code_recuptxt.setText("");
            }
        }


    }//GEN-LAST:event_btnEajouterActionPerformed

    private void btnannulerajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnannulerajouterActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnannulerajouterActionPerformed

    private void new_passtxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_passtxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_passtxt2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEajouter;
    private javax.swing.JButton btnannulerajouter;
    private javax.swing.JTextField code_recuptxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField new_passtxt1;
    private javax.swing.JTextField new_passtxt2;
    // End of variables declaration//GEN-END:variables
}
