/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import connexion.User;
import java.util.List;

/**
 *
 * @author aithmad
 */
public class Recuperation_Email extends javax.swing.JFrame {

    /**
     * Creates new form Recuperation_Email
     */
    Main principal = null;
    private StringBuilder code;
    private String email = "";

    public Recuperation_Email(Main principal) {
        initComponents();
        this.principal = principal;
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public StringBuilder getCode() {
        return code;
    }

    public String getEmail() {
        return email;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        email_recuptxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        envoyee_email_recup = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        envoyee_email_recup1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(37, 138, 122));

        jLabel1.setForeground(new java.awt.Color(236, 244, 240));
        jLabel1.setText("Email de récupération");

        envoyee_email_recup.setBackground(new java.awt.Color(97, 189, 114));
        envoyee_email_recup.setText("Envoyer");
        envoyee_email_recup.setBorderPainted(false);
        envoyee_email_recup.setOpaque(true);
        envoyee_email_recup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envoyee_email_recupActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("URW Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(244, 253, 252));
        jLabel2.setText("EMAIL DE RÉCUPÉRATION");

        envoyee_email_recup1.setBackground(new java.awt.Color(191, 215, 85));
        envoyee_email_recup1.setText("Annuler");
        envoyee_email_recup1.setBorderPainted(false);
        envoyee_email_recup1.setOpaque(true);
        envoyee_email_recup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envoyee_email_recup1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(envoyee_email_recup, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(envoyee_email_recup1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(email_recuptxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_recuptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(envoyee_email_recup)
                    .addComponent(envoyee_email_recup1))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void envoyee_email_recupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envoyee_email_recupActionPerformed
        email = email_recuptxt.getText();
        List<String> emails = User.getAllemails();
        String recup_message = "Votre code de récupération est : ";
        String recup_subject = "ProgStation – Code de récupération";

        if (!email.isEmpty()) {
            if (emails.contains(email)) {
                Random rand = new Random();
                code = new StringBuilder();

                for (int i = 0; i < 10; i++) {
                    int d = rand.nextInt(10);
                    code.append(d);
                }
                try {
                    this.principal.sendLoginEmail(email, recup_message + code, recup_subject);
                    JOptionPane.showMessageDialog(this, "Un code de récupération a été envoyé à \n" + email);
                    this.setVisible(false);
                    Reanitilisation_Password rp = new Reanitilisation_Password(this);
                    rp.setLocationRelativeTo(null);
                    rp.setVisible(true);
                } catch (Exception e) {
                    JOptionPane.showConfirmDialog(this, "Problème de connexion");
                    System.out.println(e.getMessage());
                }
            }else JOptionPane.showMessageDialog(this, 
                    "Aucun compte n’est créé avec cette adresse e-mail",
                    "Important",JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Le champ est vide",
                    "Important",JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_envoyee_email_recupActionPerformed

    private void envoyee_email_recup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envoyee_email_recup1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_envoyee_email_recup1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email_recuptxt;
    private javax.swing.JButton envoyee_email_recup;
    private javax.swing.JButton envoyee_email_recup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
